spring.application.name=LoanApplicationModule
server.port=9093

enquiry.url=http://localhost:9091/enquiry/getByLoanStatus

#database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bankcorp
spring.datasource.username=root

spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#smtp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pujaphalke1997@gmail.com
spring.mail.password=aiyg ivaq ispz izli
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties..mail.smtp.starttls.required=true
spring.mail.properties..mail.smtp.ssl.trust=*


